# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a949f2f378cd3b386066309303cb01242167bb28752b812c1c75e937542254a71f163344b6a1674f47cc12f7ad5e96ea63556192ee3914ca015ebde265f7649a

test:
  secret_key_base: 6c51524dc1fd87f8d2ff49c1a902c90925a972a7fd5dc3c2ba2e70e9dab2d2f08b72e01efbdc96fe2254aeece0eddc232514bc01e3302b40542b743350f6b8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
